services:
    phlexible_indexer_page.page_document_factory:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\PageDocumentFactory
        arguments:
            - "@phlexible_indexer.document_factory"
            - "%phlexible_indexer_page.document_class%"

    phlexible_indexer_page.page_document_builder:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\PageDocumentBuilder
        arguments:
            - "@phlexible_indexer_page.page_document_factory"
            - "@phlexible_indexer_page.document_mapper"
            - "@phlexible_indexer_page.indexible_voter"
            - "@event_dispatcher"

    phlexible_indexer_page.page_indexer:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\PageIndexer
        arguments:
            - "@phlexible_indexer_page.page_document_builder"
            - "@phlexible_indexer_page.storage"
            - "@phlexible_indexer_page.page_content_identifier"
            - "@phlexible_queue.job_manager"
            - "@event_dispatcher"
            - "@logger"
            - "%phlexible_indexer_page.batch_size%"
        tags:
            - {name: phlexible_indexer.indexer}
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.page_content_identifier:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\PageContentIdentifier
        public: false
        arguments:
            - "@phlexible_siteroot.siteroot_manager"
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_element.element_service"
            - "@phlexible_indexer_page.indexible_voter"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.locale_parameters_generator:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\ParametersGenerator\LocaleParametersGenerator
        public: false
        tags:
            - {name: phlexible_indexer_page.param_generator, priority: 900}

    phlexible_indexer_page.parameters_generator:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\ParametersGenerator\ChainParametersGenerator
        public: false
        arguments: [[]]

    phlexible_indexer_page.content_renderer:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\ContentRenderer\ContentRenderer
        public: false
        arguments:
            - "@service_container"
            - "@router.request_context"
            - "@request_stack"
            - "@phlexible_element_renderer.configurator"
            - "@phlexible_tree.content_tree_manager"
            - "@templating"
            - "@logger"
            - "@phlexible_indexer_page.parameters_generator"
        tags:
            - {name: monolog.logger, channel: indexer}

    phlexible_indexer_page.content_title_extractor:
        class: Phlexible\Bundle\IndexerPageBundle\Indexer\ContentTitleExtractor\ContentTitleExtractor
        public: false

    # commands
    phlexible_indexer_page.command.add_all:
        class: Phlexible\Bundle\IndexerPageBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer_page.page_indexer"
        tags:
            - {name: console.command}

    phlexible_indexer_page.command.add:
        class: Phlexible\Bundle\IndexerPageBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer_page.page_indexer"
        tags:
            - {name: console.command}

    phlexible_indexer_page.command.delete:
        class: Phlexible\Bundle\IndexerPageBundle\Command\AddAllCommand
        arguments:
            - "@phlexible_indexer_page.page_indexer"
        tags:
            - {name: console.command}

    phlexible_indexer_page.command.find:
        class: Phlexible\Bundle\IndexerPageBundle\Command\FindCommand
        arguments:
            - "@phlexible_indexer_page.page_indexer"
        tags:
            - {name: console.command}

    # event listeners
    phlexible_indexer_page.listener.node:
        class: Phlexible\Bundle\IndexerPageBundle\EventListener\NodeListener
        arguments:
            - "@phlexible_indexer_page.page_indexer"
            - "%phlexible_cms.languages.available%"
        tags:
            - {name: kernel.event_subscriber}
